### ISSUE TITLE
New Release causes circular import errors when calling patch all

### ISSUE THREAD

**Issue by dangothemango** [DataDog/datadog-lambda-python#313] opened 2023-03-23 18:06 UTC
## Expected Behavior

calling ddtrace.patch_all() does not throw errors

## Actual Behavior

It throws a circular import error.

We are able to workaround by doing the following

```
import ddtrace

ddtrace.patch_all()
ddtrace.patch_all(aws_lambda=False)

.....
def handler():
.....

#at the end of the file
if ddtrace is not None:
    ddtrace.patch(aws_lambda=True)
```

## Specifications

  - Datadog Lambda Layer version: 69
  - Python version: 3.9
  
## Stacktrace
  
  ```
[ERROR] AttributeError: partially initialized module 'main' has no attribute 'handler' (most likely due to a circular import)
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/opt/python/lib/python3.9/site-packages/datadog_lambda/cold_start.py", line 86, in wrapped_method
    return original_exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/python/lib/python3.9/site-packages/datadog_lambda/handler.py", line 30, in <module>
    handler_module = import_module(modified_mod_name)
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/opt/python/lib/python3.9/site-packages/ddtrace/internal/module.py", line 216, in _exec_module
    self.loader.exec_module(module)
  File "/opt/python/lib/python3.9/site-packages/datadog_lambda/cold_start.py", line 86, in wrapped_method
    return original_exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/main.py", line 13, in <module>
    ddtrace.patch_all()
  File "/opt/python/lib/python3.9/site-packages/ddtrace/_monkey.py", line 192, in patch_all
    patch(raise_errors=False, **modules)
  File "/opt/python/lib/python3.9/site-packages/ddtrace/_monkey.py", line 232, in patch
    when_imported(module)(_on_import_factory(contrib, raise_errors=False))
  File "/opt/python/lib/python3.9/site-packages/ddtrace/vendor/wrapt/importer.py", line 284, in register
    register_post_import_hook(hook, name)
  File "/opt/python/lib/python3.9/site-packages/ddtrace/vendor/wrapt/decorators.py", line 470, in _synchronized
    return wrapped(*args, **kwargs)
  File "/opt/python/lib/python3.9/site-packages/ddtrace/vendor/wrapt/importer.py", line 82, in register_post_import_hook
    hook(module)
  File "/opt/python/lib/python3.9/site-packages/ddtrace/_monkey.py", line 157, in on_import
    imported_module.patch()
  File "/opt/python/lib/python3.9/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 150, in patch
    handler, handler_module, wrapper = _get_handler_and_module()
  File "/opt/python/lib/python3.9/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 117, in _get_handler_and_module
    handler = getattr(handler_module, handler_name)
  ```

**Comment by duncanista** [comment] 2023-03-23 20:28
Hey @dangothemango, thanks for raising this issue.

We've discovered a potential root cause of this issue. We will be working on it shortly. 
Just curious about the logic. Why are you calling `ddtrace.patch_all()` in this scenario?
I raise the question since the package `datadog_lambda` (this package, which is the Datadog Python Layer), already calls it. Just want to know more about your specific use case.

Thank you!

**Comment by duncanista** [comment] 2023-04-05 03:07
Closing per #5401

**Closed by duncanista** 2023-04-05 03:07 UTC
Labels: bug
