### ISSUE TITLE
KeyError: 'x-datadog-trace-id' when tracing is turned off.

### ISSUE THREAD

**Issue by ddhanak** [DataDog/datadog-lambda-python#339] opened 2023-06-08 18:33 UTC
## Expected Behavior
If tracing is explicitly turned off, when setting the correlation ids, we should not get the KeyError: `x-datadog-trace-id`.

## Actual Behavior
There a traceback that is printed in the logs
<img width="709" alt="image" src="https://github.com/DataDog/datadog-lambda-python/assets/16140109/b5a7a313-8ec6-4981-ace9-8fcdf18b5276">

## Steps to Reproduce the Problem

  1. Turn off tracing
  1. Execute lambda

## Specifications

  - Datadog Lambda Layer version: 43
  - Python version: 3.10
  
## Stacktrace
  
See the screenshot posted above.

**Comment by astuyve** [comment] 2023-06-08 18:36
Hey @ddhanak - thanks for reaching out!

I see you're using version 43 of this library, that's a bit old as our latest release is 73. I think this bug is a duplicate of https://github.com/DataDog/datadog-lambda-python/issues/332 and fixed via https://github.com/DataDog/datadog-lambda-python/pull/334 which is released in [v73](https://github.com/DataDog/datadog-lambda-python/releases/tag/v73).

Can you upgrade to 73 and report back?
Thanks!

**Closed** 2023-06-09 12:04 UTC

**Comment by ddhanak** [comment] 2023-06-09 12:33
@astuyve all working as expected, we were running an older version of the library.
