### ISSUE TITLE
Way to exclude the AWS Lambda Tags from shipping a metric?

### ISSUE THREAD

**Issue by djtecha** [DataDog/datadog-lambda-python#262] opened 2022-11-04 19:30 UTC
Hello,
Is there a way to disable shipping the Lambda tags with a metric? For instance when I make this call

```
        lambda_metric(
            'pagerduty.mttr.resolved.count',
            int(value["seconds"]),
            tags=['service:' + key, 'team:' + value["team"]]
        )
```
it ships the metric with a Service tag from the lambda itself so I get 2 Service tags which is not the desired effect. Instead I'd like to just ship that specific metric without inheriting the ones from the lamba tags.

**Comment by IvanTopolcic** [comment] 2022-11-08 21:59
Hey! Thanks for the report! Just out of curiosity, are you using the Datadog integration by any chance?

I'd say we should definitely overwrite the default service tags if you specify one manually. I'm not sure if this is the default behavior or not, but I can go ahead and check for you.

**Comment by IvanTopolcic** [comment] 2022-11-09 16:37
Also just to be clear, are you setting the service tag via a DD_TAGS environment variable? As in, `DD_TAGS=service:myservice`.

**Comment by djtecha** [comment] 2022-11-10 17:37
No, I removed the DD_TAGS ones because I thought that was the issue. I am using the AWS integration so maybe that's my issue where it's linking together like it should even though I don't want it to in this odd case. I'll try adding an exclusion in the integration to see if it stops showing up.

**Comment by djtecha** [comment] 2022-11-11 00:03
Disabled the integration and this still is getting these tags.

**Comment by djtecha** [comment] 2022-11-11 00:05
I have a lambda that basically grabs values from pagerduty and submits them to DD. The issue is we submit that metrics with a Service tag as Service is the logical grouping we using for all of our services. So on the time series you get a metrics with 2 service tags and it just looks bad.

**Comment by tianchu** [comment] 2023-01-31 21:30
@djtecha sorry for the late to the discussion. Are you using the Forwarder or Lambda Extension? aka, how are you submitting the custom metric https://docs.datadoghq.com/serverless/custom_metrics? Asking because I don't think we automatically add a service tag, at least not when using the extension. Also do you have env var DD_SERVICE set?

**Comment by djtecha** [comment] 2023-02-06 23:57
DD_SERVICE is not set in the env variables. And I am shipping the metric via the lambda layer Datadog-Python39

**Comment by djtecha** [comment] 2023-02-07 00:17
For reference I'm using these 2 layers
`  layers = [
    "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Python39:67",
    "arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:36"
  ]`

**Comment by tianchu** [comment] 2023-02-07 14:42
@djtecha That's unexpected and I don't reproduce it in our testing app either. Maybe you can DM me some details through our community [slack](https://github.com/DataDog/datadog-lambda-python#community)?

**Comment by tianchu** [comment] 2023-02-28 21:43
Closing per discussion over slack. 

To summarize for future readers facing similar challenges, the problem was that the Lambda function submitting the custom metric is tagged in AWS with a `service` tag for itself. The Datadog AWS integration automatically crawls Lambda resource tags from AWS and enrich them to the telemetry (including custom metrics) from the corresponding functions. This conflicts with the `service` tag directly submitted with the custom metric.

A workaround is excluding that specific Lambda function from the AWS integration. The other solution is using a different tag name, such as, `pg_service` in this case.

That said, if we do see more people running into similar problems, Datadog can potentially make it an option to disable the tag enrichment under certain conditions.

**Closed by tianchu** 2023-02-28 21:43 UTC
