### ISSUE TITLE
Werkzeug 2.0.0 is not supported

### ISSUE THREAD

**Issue by extsoft** [DataDog/datadog-lambda-python#141] opened 2021-05-17 16:52 UTC
## Expected Behavior

If [Flask 2.0.0](https://pypi.org/project/Flask/2.0.0/) is used in AWS Lambda function, it brings [Werkzeug 2.0.0](https://pypi.org/project/Werkzeug/2.0.0/) as a transitive dependency. Both these packages remove Python 2 suport.

When `serverless-plugin-datadog 2.22.0` is used, it should run the Datadog handler successfully.

## Actual Behavior
The Lambda crashes. The error:
```text
[ERROR] Runtime.ImportModuleError: Unable to import module 'datadog_lambda.handler': No module named 'werkzeug._compat'
Traceback (most recent call last):
```

> Please note, Flask and Werkzeug < 2.0.0 work fine.

## Steps to Reproduce the Problem

  1. Create Lambda function with [Flask 2.0.0](https://pypi.org/project/Flask/2.0.0/) 
  2. Add  `serverless-plugin-datadog 2.22.0` to Serverless configuration
  3. Deploy and run the Lambda

## Specifications

  - Datadog Lambda Layer version: arn:aws:lambda:**********:464622532012:layer:Datadog-Python38:34
  - Python version: 3.8
  
## Stacktrace
  
  ```
[ERROR] Runtime.ImportModuleError: Unable to import module 'datadog_lambda.handler': No module named 'werkzeug._compat'
Traceback (most recent call last):
  ```

**Comment by saraducks** [comment] 2021-07-02 03:49
Facing similar issues, I do have the same python version and serverless-plugin-datatdog version. 

[ERROR] Runtime.ImportModuleError: Unable to import module 'datadog_lambda.handler': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
Traceback (most recent call last):

**Comment by tianchu** [comment] 2021-09-14 13:18
@extsoft I have been trying to reproduce this issue but interrupted by some personal matters (had to take time off). This is on my priorities list and I should be able to get to it pretty soon.

**Comment by tianchu** [comment] 2021-09-15 02:42
@extsoft and for anyone running into the same issue, the error is not actually from the Datadog code, but instead is bubbled up from another dependency that your application uses. 'datadog_lambda.handler' shows up in the stack trace simply because our plugin makes the datadog handler wrap around your original handler and that's why it shows up at the top of the stack trace. 

Some research led me to this know issue https://github.com/logandk/serverless-wsgi/issues/179 of the serverless-wsgi plugin, and the issue seems to be fixed very recently in version 2.0.0. If you are using this plugin to run your flask application, can you try upgrade? If not, can you help provide a complete copy of stack trace of the error and a minimal sample application (e.g., serverless.yml and the handler function)?

**Comment by tianchu** [comment] 2021-09-24 15:22
Closing since the error is not actually from the Datadog codebase. For whoever runs into this issue, please checkout https://github.com/logandk/serverless-wsgi/issues/179. 

Feel free to reopen if anyone can help provide more evidence that code changes are required in the Datadog codebase.

**Closed by tianchu** 2021-09-24 15:22 UTC
Labels: dd-to-triage

**Comment by extsoft** [comment] 2021-10-06 15:08
@tianchu thank you so much for the research you made! The error is from `serverless-wsgi` and all work perfectly if it is updated to the latest version.
