### ISSUE TITLE
Unclear compatibility requirements between datadog-lambda and lambda-extension

### ISSUE THREAD

**Issue by ebarti** [DataDog/datadog-lambda-python#291] opened 2023-01-03 11:40 UTC
Following the instructions listed within https://docs.datadoghq.com/serverless/installation/python?tab=containerimage , it specifies that `Note that the minor version of the datadog-lambda package always matches the layer version. For example, datadog-lambda v0.5.0 matches the content of layer version 5.` 

However, datadog-lambda is currently at version `4.66.0`, but the layer is only at version `34`. Additionally, how versioning is being done via tags here is also really confusing: tags do not match version levels, and there are even some tag releases that did not update the package revision, yielding no new published packages in pypi - example: tags `v61` and `v62`

## Expected Behavior
I can quickly pinpoint which datadog-lambda package version I need for a given layer version.

## Actual Behavior
datadog-lambda and layer versioning do not follow an understandable versioning strategy, resulting in trial and error approaches.

**Comment by tianchu** [comment] 2023-01-04 18:41
@ebarti datadog-lambda's minor version (currently at 4.66.0) is expected to match the Python Lambda Layer version (66). See the release https://github.com/DataDog/datadog-lambda-python/releases/tag/v66. 

The confusing part is that we do have another Lambda Layer for the language-agnostic Lambda Extension (aka the agent), which is currently at v35 https://github.com/DataDog/datadog-lambda-extension/releases/tag/v35.

I hope this clarifies things for you.

**Comment by ebarti** [comment] 2023-01-08 11:57
Exactly! So if we are building a custom docker image with the language-agnostic extension (agent) as the [instructions list](https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage), what would be the compatibility here?

**Comment by tianchu** [comment] 2023-01-11 19:48
@ebarti I assume you want to pin down the versions instead of pulling in the latest automatically on each build? If so, I would recommend pulling in the latest versions in the first build, test, if you are satisfied, and then pin down to those versions. BTW I don't think there are that much compatibility concern between the extension and the runtime-specific library (e.g., tracer), they are only loosely coupled.

**Comment by ebarti** [comment] 2023-01-11 20:23
Ok let me backtrack to why I am asking all of this. Basically, we had a lambda that failed to run due an `ImportModuleError`.

```bash
Runtime.ImportModuleError: Unable to import module 'datadog_lambda.handler': No module named 'datadog_lambda.handler'
```

The lambda had a container image built with:
```dockerfile
COPY --from=public.ecr.aws/datadog/lambda-extension:23 /opt/extensions/ /opt/extensions
```

And was using the `datadog-lambda` package at 0.0.4

After upgrading the extension to layer `66`, and `datadog-lambda>=3.52.0,<4.0.0` the lambda did not have the import errror.

Additionally, I have run into issues anytime I try to use `datadog-lambda > 4.0.0` and any version of the `datadog/lambda-extension`

**Comment by joeyzhao2018** [comment] 2023-01-11 21:12
Hi @ebarti , this `ImportModuleError` is usually due to missing `datadog-lambda-python` layer, whose latest version is at `4.66.0`. So its layer version is `66`. 
As for the `datadog/lambda-extension`, its layer version is `35` at `public.ecr.aws/datadog/lambda-extension:35` .
They are two different layers loosely coupled as @tianchu mentioned.

Could you please elaborate more on the other issues besides the `ImportModuleError`? Thank you.

**Comment by ebarti** [comment] 2023-01-15 07:33
Hey @joeyzhao2018 thank you for your response. Basically I was following the i[nstructions listed in the Datadog's documentation site](https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage) where, in order to build custom images, one is instructed to install the language-agnostic datadog-lambda extension + the datadog-lambda python package. 

The resulting Docker image targets `datadog_lambda.handler.handler` as the CMD, and we inject the actual handler function via the `DD_LAMBDA_HANDLER` environment variable. 

We expeirenced the `ImportModuleError` when using datadog-lambda > 4.0.0 and any version of the language agnostic datadog/lambda-extension, and when we used the layer version 23 and datadog-lambda at 0.0.4

**Comment by tianchu** [comment] 2023-01-17 22:04
@ebarti Can you tell us a bit more about your specific set up when experiencing the ImportModuleError? Our internal self-monitoring app has these relatively new versions installed and working just fine https://a.cl.ly/YEuDe9ro. The dockerfile for the self-monitoring app is pasted below for your reference as well.

```
FROM --platform=linux/amd64 public.ecr.aws/datadog/lambda-extension:latest AS datadog
FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.8

COPY --from=datadog /opt/extensions/ /opt/extensions

COPY python.py ./

RUN pip install datadog-lambda

CMD ["datadog_lambda.handler.handler"]
```

In short, we are not aware of that issue, nor we know how to reproduce it.

**Comment by astuyve** [comment] 2023-02-14 08:24
Closing this as there's been no update for some time. If you're still experiencing this issue, please feel free to re-open. Thanks!

**Closed by astuyve** 2023-02-14 08:24 UTC
