### ISSUE TITLE
Error in `tags.py`: ValueError: not enough values to unpack (expected 7, got 5)

### ISSUE THREAD

**Issue by jspreddy** [DataDog/datadog-lambda-python#76] opened 2020-08-24 18:18 UTC
## Expected Behavior
When running the function locally using `serverless invoke local`, I should not get this error.

## Actual Behavior
Getting an error:
```
ValueError: not enough values to unpack (expected 7, got 5)
```

## Steps to Reproduce the Problem

  1. Instrument the lambda function, not using the serverless plugin, but directly using the lambda layer on the lambda function.
  1. Run the Lambda function locally using `serverless invoke local`
  1. Observe the error

## Specifications

  - Datadog Lambda Layer version:  `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Python36:19`
  - Python version: `Python 3.6.10`
  
## Stacktrace
  
```
Traceback (most recent call last):
  File "<my-project-path>/.venv/lib/python3.6/site-packages/datadog_lambda/wrapper.py", line 117, in _before
    submit_invocations_metric(context)
  File "<my-project-path>/.venv/lib/python3.6/site-packages/datadog_lambda/metric.py", line 103, in submit_invocations_metric
    submit_enhanced_metric("invocations", lambda_context)
  File "<my-project-path>/.venv/lib/python3.6/site-packages/datadog_lambda/metric.py", line 93, in submit_enhanced_metric
    tags=get_enhanced_metrics_tags(lambda_context),

  File "<my-project-path>/.venv/lib/python3.6/site-packages/datadog_lambda/tags.py", line 84, in get_enhanced_metrics_tags
    return parse_lambda_tags_from_arn(lambda_context) + [
  File "<my-project-path>/.venv/lib/python3.6/site-packages/datadog_lambda/tags.py", line 43, in parse_lambda_tags_from_arn
    _, _, _, region, account_id, _, function_name = split_arn
ValueError: not enough values to unpack (expected 7, got 5)
```

The arn of the function from the `lambda_context.invoked_function_arn` looks like this:

```
arn:aws:lambda:serverless:my-lambda-function-name
```

### Error here: 
https://github.com/DataDog/datadog-lambda-python/blob/master/datadog_lambda/tags.py#L43

**Comment by jspreddy** [comment] 2020-08-24 18:35
Updated the ticket with 
1. lambda layer arn 
1. Steps to reproduce: instrumentation clarification.

**Comment by jspreddy** [comment] 2020-08-24 18:35
![serverless-yml-lambda-function](https://user-images.githubusercontent.com/2302194/91082701-0a51f100-e617-11ea-97b2-20a380914c37.png)

**Comment by tianchu** [comment] 2020-08-27 17:29
Looks like the issue is that `sls invoke local` passes in a fake lambda arn that is different from the actual arn format. You might be able to workaround the issue by overriding the context object using [--context](https://www.serverless.com/framework/docs/providers/aws/cli-reference/invoke-local/).

**Comment by Czechh** [comment] 2020-09-14 20:56
@jspreddy were you able to test my teammate's suggestion?

**Comment by tianchu** [comment] 2021-08-05 03:36
@jspreddy I'm closing this issue assuming you already figured something out :) 

One more thing to point out, majority of our customers using serverless framework would use our [plugin](https://docs.datadoghq.com/serverless/installation/python?tab=serverlessframework) to make the necessary configuration changes for instrumentation, and the plugin does not make these changes when invoking functions locally. In other words, using the plugin would also help you avoid this issue.

**Closed by tianchu** 2021-08-05 03:36 UTC
Labels: dd-to-triage
